java -cp ../lib/hamcrest-core-1.3.jar:../lib/junit-4.13.2.jar:../../../EXE/Tests:. org.junit.runner.JUnitCore test.domini.AutorTest
java -cp ../lib/hamcrest-core-1.3.jar:../lib/junit-4.13.2.jar:../../../EXE/Tests:. org.junit.runner.JUnitCore test.domini.DocumentTest
java -cp ../lib/hamcrest-core-1.3.jar:../lib/junit-4.13.2.jar:../../../EXE/Tests:. org.junit.runner.JUnitCore test.domini.ParaulaTest
java -cp ../lib/hamcrest-core-1.3.jar:../lib/junit-4.13.2.jar:../../../EXE/Tests:. org.junit.runner.JUnitCore test.domini.ExpBoolTest
java -cp ../lib/hamcrest-core-1.3.jar:../lib/junit-4.13.2.jar:../../../EXE/Tests:. org.junit.runner.JUnitCore test.domini.IndexExpBoolTest
java -cp ../lib/hamcrest-core-1.3.jar:../lib/junit-4.13.2.jar:../../../EXE/Tests:. org.junit.runner.JUnitCore test.domini.IndexAutorsTest
java -cp ../lib/hamcrest-core-1.3.jar:../lib/junit-4.13.2.jar:../../../EXE/Tests:. org.junit.runner.JUnitCore test.domini.IndexDocumentTest
java -cp ../lib/hamcrest-core-1.3.jar:../lib/junit-4.13.2.jar:../../../EXE/Tests:. org.junit.runner.JUnitCore test.domini.IndexParaulaTest
java -cp ../lib/hamcrest-core-1.3.jar:../lib/junit-4.13.2.jar:../../../EXE/Tests:. org.junit.runner.JUnitCore test.utils.UtilsTest
java -cp ../lib/hamcrest-core-1.3.jar:../lib/junit-4.13.2.jar:../../../EXE/Tests:. org.junit.runner.JUnitCore test.utils.NodeTest
java -cp ../lib/hamcrest-core-1.3.jar:../lib/junit-4.13.2.jar:../../../EXE/Tests:. org.junit.runner.JUnitCore test.utils.PairTest
